use ecommerce_db;
Select * from olist_customers_dataset limit 5;
select * from olist_orders_dataset limit 5;
select * from olist_order_items_dataset limit 5;
select * from olist_products_dataset limit 5;
select * from olist_customers_dataset limit 10;
select * from olist_order_items_dataset where price>100;
select * from olist_order_items_dataset order by price desc;
select customer_id, count(*) as total_orders from olist_orders_dataset group by customer_id;
select c.customer_city, o.order_status from olist_customers_dataset c inner join olist_orders_dataset o on c.customer_id=o.customer_id;
select c.customer_id, o.order_status from olist_customers_dataset c left join olist_orders_dataset o on c.customer_id=o.customer_id; 
select Avg(price) as average_price from olist_order_items_dataset; 
select Sum(price) as total_sales from olist_order_items_dataset;
select * from olist_order_items_dataset where price>( select avg(price) from olist_order_items_dataset );
create view customer_order_summary as select c.customer_id, c.customer_city, o.order_status from olist_customers_dataset c join olist_orders_dataset o on c.customer_id=o,customer_id;
desc olist_customers_dataset;
desc olist_orders_dataset;
create view customer_order_summary as select c.customer_id, c.customer_city, o.order_status from olist_customers_dataset c inner join olist_orders_dataset o on c.customer_id=o.customer_id;
select * from customer_order_summary limit 10;
create INDEX idx_customer_id on olist_orders_dataset(customer_id);
desc olist_customers_dataset; 
create index idx_customer_id on olist_customers_dataset(customer_id(20));
show index from olist_customers_dataset;